[package]
name = "gravity-go"
version = "0.1.0"
edition = "2021"

[dependencies]
genco = { workspace = true }
anyhow = { workspace = true }
heck = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4"
