[package]
name = "gravity-wit"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-core = { workspace = true }
wit-component = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4"
