package arcjet:example;

interface logger {
  debug: func(msg: string);
  log: func(msg: string);
  warn: func(msg: string);
  error: func(msg: string);
}

world basic {
  import logger;

  export hello: func() -> result<string, string>;
}
