package arcjet:basic;

interface logger {
  debug: func(msg: string);
  info: func(msg: string);
  warn: func(msg: string);
  error: func(msg: string);
}

world basic {
  import logger;

  export hello: func() -> result<string, string>;
}
