// Code generated by wit-bindgen-go. DO NOT EDIT.

package basic

import (
	"go.bytecodealliance.org/cm"
)

func lift_OptionBool(f0 uint32, f1 uint32) (v cm.Option[bool]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[bool])(cm.Some[bool]((bool)(cm.U32ToBool((uint32)(f1)))))
}

func lift_OptionString(f0 uint32, f1 *uint8, f2 uint32) (v cm.Option[string]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[string])(cm.Some[string](cm.LiftString[string]((*uint8)(f1), (uint32)(f2))))
}
