// Code generated by wit-bindgen-go. DO NOT EDIT.

package basic

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "arcjet:basic/basic".
var Exports struct {
	// Hello represents the caller-defined, exported function "hello".
	//
	// Say hello.
	//
	//	hello: func() -> result<string, string>
	Hello func() (result cm.Result[string, string, string])

	// Primitive represents the caller-defined, exported function "primitive".
	//
	// Just return a bool primitive.
	//
	//	primitive: func() -> bool
	Primitive func() (result bool)

	// OptionalPrimitive represents the caller-defined, exported function "optional-primitive".
	//
	// Return an optional bool primitive.
	//
	//	optional-primitive: func(b: option<bool>) -> option<bool>
	OptionalPrimitive func(b cm.Option[bool]) (result cm.Option[bool])

	// ResultPrimitive represents the caller-defined, exported function "result-primitive".
	//
	// Return a result with an error.
	//
	//	result-primitive: func() -> result<bool, string>
	ResultPrimitive func() (result cm.Result[string, bool, string])

	// OptionalString represents the caller-defined, exported function "optional-string".
	//
	// Return an optional string.
	//
	//	optional-string: func(s: option<string>) -> option<string>
	OptionalString func(s cm.Option[string]) (result cm.Option[string])
}
