// Code generated by wit-bindgen-go. DO NOT EDIT.

package basic

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// This file contains wasmimport and wasmexport declarations for "arcjet:basic".

//go:wasmexport hello
//export hello
func wasmexport_Hello() (result unsafe.Pointer) {
	result_ := Exports.Hello()
	result = unsafe.Pointer(&result_)
	return
}

//go:wasmexport primitive
//export primitive
func wasmexport_Primitive() (result0 uint32) {
	result := Exports.Primitive()
	result0 = (uint32)(cm.BoolToU32(result))
	return
}

//go:wasmexport optional-primitive
//export optional-primitive
func wasmexport_OptionalPrimitive(b0 uint32, b1 uint32) (result *cm.Option[bool]) {
	b := lift_OptionBool((uint32)(b0), (uint32)(b1))
	result_ := Exports.OptionalPrimitive(b)
	result = &result_
	return
}

//go:wasmexport result-primitive
//export result-primitive
func wasmexport_ResultPrimitive() (result unsafe.Pointer) {
	result_ := Exports.ResultPrimitive()
	result = unsafe.Pointer(&result_)
	return
}

//go:wasmexport optional-string
//export optional-string
func wasmexport_OptionalString(s0 uint32, s1 *uint8, s2 uint32) (result unsafe.Pointer) {
	s := lift_OptionString((uint32)(s0), (*uint8)(s1), (uint32)(s2))
	result_ := Exports.OptionalString(s)
	result = unsafe.Pointer(&result_)
	return
}
