// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package logger represents the imported interface "arcjet:basic/logger".
//
// A logger interface.
package logger

import (
	"go.bytecodealliance.org/cm"
)

// Debug represents the imported function "debug".
//
// Emit a log message at the debug level.
//
//	debug: func(msg: string)
//
//go:nosplit
func Debug(msg string) {
	msg0, msg1 := cm.LowerString(msg)
	wasmimport_Debug((*uint8)(msg0), (uint32)(msg1))
	return
}

// Info represents the imported function "info".
//
// Emit a log message at the info level.
//
//	info: func(msg: string)
//
//go:nosplit
func Info(msg string) {
	msg0, msg1 := cm.LowerString(msg)
	wasmimport_Info((*uint8)(msg0), (uint32)(msg1))
	return
}

// Warn represents the imported function "warn".
//
// Emit a log message at the warn level.
//
//	warn: func(msg: string)
//
//go:nosplit
func Warn(msg string) {
	msg0, msg1 := cm.LowerString(msg)
	wasmimport_Warn((*uint8)(msg0), (uint32)(msg1))
	return
}

// Error represents the imported function "error".
//
// Emit a log message at the error level.
//
//	error: func(msg: string)
//
//go:nosplit
func Error(msg string) {
	msg0, msg1 := cm.LowerString(msg)
	wasmimport_Error((*uint8)(msg0), (uint32)(msg1))
	return
}
