// Code generated by wit-bindgen-go. DO NOT EDIT.

package logger

// This file contains wasmimport and wasmexport declarations for "arcjet:basic".

//go:wasmimport arcjet:basic/logger debug
//go:noescape
func wasmimport_Debug(msg0 *uint8, msg1 uint32)

//go:wasmimport arcjet:basic/logger info
//go:noescape
func wasmimport_Info(msg0 *uint8, msg1 uint32)

//go:wasmimport arcjet:basic/logger warn
//go:noescape
func wasmimport_Warn(msg0 *uint8, msg1 uint32)

//go:wasmimport arcjet:basic/logger error
//go:noescape
func wasmimport_Error(msg0 *uint8, msg1 uint32)
